### PR TITLE
The update

### PR DESCRIPTION
**Pull request by mimi89999**
The update ;-)

### CODE REVIEW

**Comment by mimi89999** [comment]
Wha adding/creating issues is disabled?

**Comment by mimi89999** [comment]
*why

**Comment by otakuchiyan** [comment]
I don't know why adding/creating issue is disabled. I am never changed the settings about issue.
I have been tried to make it enabled on my phone. But seems failed.

**Comment by otakuchiyan** [comment]
Thank you.

**Comment by mimi89999** [comment]
@otakuchiyan In the repo, go to settings: https://github.com/otakuchiyan/Wifi-Key-View/settings (I don't know if this link will work...)
Under "Features" activate "Issues"...
capture du 2015-08-31 11 47 57

**Comment by otakuchiyan** [comment]
I have been tried to reopen issue features 2 times on my phone.
But failed again with no reasons. I think we should give up to reopen the issue because it isn't very important.

**Pull request merged**
