### PR TITLE
Fix showing unwanted parts of /data/misc/wifi/wpa_supplicant.conf file

### PR DESCRIPTION
**Pull request by mimi89999**
Fix showing unwanted parts of /data/misc/wifi/wpa_supplicant.conf file.

### CODE REVIEW

**Comment by mimi89999** [comment]
I'm also updating the app to Material Theme but I don't know which one to choose...
img_20150830_205901
img_20150830_205953
img_20150830_205749

**Comment by otakuchiyan** [comment]
I like material dark. So I choice the theme which had dark background and dark actionbar.

**Comment by mimi89999** [comment]
Why didn't you merge this PR? It fixes an issue where "scan_SSID: 1" is shown...
tmp_31785-screenshot_2015-08-31-18-38-06-84279658

**Comment by otakuchiyan** [comment]
I have to use phone on this week, which it only support 2G netowrk.
I can't merge this pull request may because the network is too slow or the browser had bugs.
I have been clicked "Merge pull request" button 10 times, but nothing happens.

**Pull request merged**
